In [40]:
import os
ROOT='/content/drive/MyDrive/Colab Notebooks/CNN'


In [41]:
os.chdir(ROOT)
os.getcwd()

'/content/drive/MyDrive/Colab Notebooks/CNN'

In [42]:
import tensorflow as tf


In [43]:
tf.__version__

'2.8.0'

In [44]:
import tensorflow as tf 
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalAveragePooling2D

In [45]:
from keras.datasets import mnist
# use Keras to import pre-shuffled MNIST database
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [46]:
X_train = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255 

In [47]:
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

X_train shape: (60000, 28, 28)
60000 train samples
10000 test samples


In [48]:
from keras.utils import np_utils

num_classes = 10 
# print first ten (integer-valued) training labels
print('Integer-valued labels:')
print(y_train[:10])

# one-hot encode the labels
# convert class vectors to binary class matrices
y_train = np_utils.to_categorical(y_train, num_classes)
y_test = np_utils.to_categorical(y_test, num_classes)

# print first ten (one-hot) training labels
print('One-hot labels:')
print(y_train[:10])

Integer-valued labels:
[5 0 4 1 9 2 1 3 1 4]
One-hot labels:
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [49]:
# input image dimensions 28x28 pixel images. 
img_rows, img_cols = 28, 28

X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

print('input_shape: ', input_shape)
print('x_train shape:', X_train.shape)


input_shape:  (28, 28, 1)
x_train shape: (60000, 28, 28, 1)


In [51]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalAveragePooling2D,Activation

model = Sequential()

model.add(Conv2D(10,kernel_size=(3,3,),padding='same',activation='relu',input_shape=input_shape))#26
model.add(Conv2D(16, (3, 3),padding='same', activation='relu'))#24
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(16, kernel_size=(3,3),padding='same', activation='relu'))#12
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.1))
model.add(Conv2D(16,kernel_size=(3,3),padding='same', activation='relu'))#6
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(10,kernel_size=(3,3,)))#1
model.add(Flatten())
model.add(Activation('softmax'))




In [52]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_54 (Conv2D)          (None, 28, 28, 10)        100       
                                                                 
 conv2d_55 (Conv2D)          (None, 28, 28, 16)        1456      
                                                                 
 max_pooling2d_30 (MaxPoolin  (None, 14, 14, 16)       0         
 g2D)                                                            
                                                                 
 conv2d_56 (Conv2D)          (None, 14, 14, 16)        2320      
                                                                 
 max_pooling2d_31 (MaxPoolin  (None, 7, 7, 16)         0         
 g2D)                                                            
                                                                 
 dropout_10 (Dropout)        (None, 7, 7, 16)        

In [55]:
# We are importing the Adam Optimizer
from tensorflow.keras.optimizers import Adam

# We are importing the learningratescheduler callback
from keras.callbacks import LearningRateScheduler
#Creating the "scheduler" function with two arguments i.e learningrate and epoch
def scheduler(epoch, lr):
  return round(0.003 * 1/(1 + 0.319 * epoch), 10)

#	LearningRate = LearningRate * 1/(1 + decay * epoch) here decay is 0.319 and epoch is 10.

# here we are compiling our model and using 'categorical_crossentropy' as our loss function and adam as our optimizer with learning rate =0.003 and metrics is accuracy

model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.003), metrics=['accuracy'])

# Here we are traing our model using the data and using batch size of 128,number of epochs are 20 and using verbose=1 for printing out all the results.
# In the callbacks parameter we are using the LearningRateScheduler which takes two arguments scheduler function which we built earlier to reduce the learning rate in each decay and verbose =1
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_test, y_test), callbacks=[LearningRateScheduler(scheduler, verbose=1)])


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)



Epoch 1: LearningRateScheduler setting learning rate to 0.003.
Epoch 1/20
469/469 [==============================] - 16s 13ms/step - loss: 0.2888 - accuracy: 0.9080 - val_loss: 0.0778 - val_accuracy: 0.9749 - lr: 0.0030

Epoch 2: LearningRateScheduler setting learning rate to 0.0022744503.
Epoch 2/20
469/469 [==============================] - 5s 11ms/step - loss: 0.0820 - accuracy: 0.9745 - val_loss: 0.0507 - val_accuracy: 0.9828 - lr: 0.0023

Epoch 3: LearningRateScheduler setting learning rate to 0.0018315018.
Epoch 3/20
469/469 [==============================] - 5s 10ms/step - loss: 0.0599 - accuracy: 0.9814 - val_loss: 0.0467 - val_accuracy: 0.9847 - lr: 0.0018

Epoch 4: LearningRateScheduler setting learning rate to 0.0015329586.
Epoch 4/20
469/469 [==============================] - 5s 11ms/step - loss: 0.0499 - accuracy: 0.9840 - val_loss: 0.0346 - val_accuracy: 0.9878 - lr: 0.0015

Epoch 5: LearningRateScheduler setting learning rate to 0.0013181019.
Epoch 5/20
469/469 [=======